/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "qcihmqgvzozjnlelufvb"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFjaWhtcWd2em96am5sZWx1ZnZiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzIyMzg3NzQsImV4cCI6MjA4NzgxNDc3NH0.na-xiI-E8_0B-dkCX6NYCLoJTpL9fuce9IaSMyAkzQM"